### ISSUE TITLE
Compiler Errors With JSON.hpp

### ISSUE THREAD

**Issue by 06needhamt** [nlohmann/json#265]
Hi i am experiencing some compiler errors with JSON.hpp the errors are as follows
```
Error	C2589	'(': illegal token on right side of '::'	json.hpp 8475	
Error	C2059	syntax error: '::'   json.hpp	8475	
Error	C2143	syntax error: missing '(' before '::'	json.hpp	8475	
Error	C2589	'(': illegal token on right side of '::'	json.hpp	8481	
Error	C2059	syntax error: '::'	json.hpp	8481	
Error	C2143	syntax error: missing '(' before '::'	json.hpp	8481	
```
This was compiled using Visual Studio 2015 Update 2 on Windows 10 build 10586

Hope this helps fix the issue

**Comment by gregmarr** [comment]
I'm guessing that this is the same issue as:
https://github.com/nlohmann/json/issues/260

If not, please give the text of the line that shows the error, since 8481 in the latest code is a blank line.

**Comment by nlohmann** [comment]
I agree with @gregmarr.

@06needhamt, could you please try the latest version of the develop branch? I just merged a fix for the related issue #260 which should fix your problem as well.

**Comment by 06needhamt** [comment]
@nlohmann The issue still occurrs for me when using the develop branch with the error now occuring on line 8507.
However i have made a fix and will send PR shortly

**Comment by 06needhamt** [comment]
See PR https://github.com/nlohmann/json/pull/266

**Comment by nlohmann** [comment]
Merged #266. Thanks a lot!
